name: siapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8  
  flutter_flow_chart: ^3.2.3
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  sqflite: ^2.3.3  # Usa una versión estable
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  youtube_player_flutter: ^9.1.1
  webview_flutter: ^4.11.0
  webview_flutter_wkwebview: ^3.20.0
  webview_flutter_android: ^4.4.0
  confetti: ^0.8.0
  lottie: ^3.3.1
  flutter_spinkit: ^5.2.1
  flutter_animate: ^4.5.2
  fluttertoast: ^8.2.2
  flutter_highlighter: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/module1.json  
    - assets/data/module2.json
    - assets/data/module3.json
    - assets/data/module4.json  
    - assets/data/module2/tema1.json
    - assets/data/module2/tema2.json
    - assets/data/module2/tema3.json
    - assets/data/module2/tema4.json
    - assets/data/module2/actividades.json
    - assets/data/module4/tema1.json
    - assets/data/module4/tema2.json
    - assets/data/module4/tema3.json
    - assets/data/module4/tema4.json
    - assets/data/module4/actividades.json


flutter_icons:
  android: "adaptive"  # Ícono adaptativo para Android
  ios: true           # Ícono tradicional para iOS
  image_path: "assets/icon/SIAAP.png"  # Mismo logo para ambos sistemas
  
  # Android (ícono adaptativo con colores)
  adaptive_icon_background: "#FF6B6B"  # Color de fondo (usa tu color favorito)
  adaptive_icon_foreground: "assets/icon/SIAAP.png"  # Tu logo transparente

  # iOS (opcional: mismo ícono para modo claro/oscuro)
  image_path_ios: "assets/icon/SIAAP.png"  # Si omites esto, usará image_path
