// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBME_KoBFqNx1Mh6XwpMoSmIiYHU9vYhew',
    appId: '1:23727340627:web:2207a8164bb88482949aa6',
    messagingSenderId: '23727340627',
    projectId: 'tecapp-d6dd0',
    authDomain: 'tecapp-d6dd0.firebaseapp.com',
    storageBucket: 'tecapp-d6dd0.firebasestorage.app',
    measurementId: 'G-GDHEKEVL7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeoKTL7BXxl1J0B2yOuJWTFLrO4GT09b8',
    appId: '1:23727340627:android:33442832315a4306949aa6',
    messagingSenderId: '23727340627',
    projectId: 'tecapp-d6dd0',
    storageBucket: 'tecapp-d6dd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw1jGyLLmoD1MUocF1NVJ4eZbSPI4EXew',
    appId: '1:23727340627:ios:3963f7351480e517949aa6',
    messagingSenderId: '23727340627',
    projectId: 'tecapp-d6dd0',
    storageBucket: 'tecapp-d6dd0.firebasestorage.app',
    iosBundleId: 'com.example.siapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw1jGyLLmoD1MUocF1NVJ4eZbSPI4EXew',
    appId: '1:23727340627:ios:3963f7351480e517949aa6',
    messagingSenderId: '23727340627',
    projectId: 'tecapp-d6dd0',
    storageBucket: 'tecapp-d6dd0.firebasestorage.app',
    iosBundleId: 'com.example.siapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBME_KoBFqNx1Mh6XwpMoSmIiYHU9vYhew',
    appId: '1:23727340627:web:d6bc22184cf9129d949aa6',
    messagingSenderId: '23727340627',
    projectId: 'tecapp-d6dd0',
    authDomain: 'tecapp-d6dd0.firebaseapp.com',
    storageBucket: 'tecapp-d6dd0.firebasestorage.app',
    measurementId: 'G-M29GJF4W4G',
  );
}
